### PR TITLE
Fixed Path assignment in subvolume Info structure

### PR DESCRIPTION
**Pull request by asv**
Path field did not change in subvolMap func, becouse by semantics "for _, v := range" loop returns _copy_ of value. Propose, to reduce unnecessary copy, use pointers instead of values in the map Info.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
ping @stevvooe

**Comment by stevvooe** [comment]
LGTM

This could also be fixed by simply addressing map when path is assigned.

**Comment by stevvooe** [comment]
@dmcgowan PTAL

**Comment by dmcgowan** [comment]
LGTM

**Comment by stevvooe** [comment]
@asv One small request: could you sign your commit for DCO?

Just `git commit -s --amend` and the force push the branch.

Let me know if that's a problem.

**Comment by asv** [comment]
Signed.

**Comment by stevvooe** [comment]
@asv Thanks for signing with the GPG key, but you also need to sign off with DCO on the commit. When doing both, with git, you'll use a command like `git commit -sS --amend`.

Sorry for the back and forth.

**Comment by asv** [comment]
@stevvooe Done. Sorry for my inattention.

**Comment by dmcgowan** [comment]
@asv thanks for updating and your patience!

**Comment by stevvooe** [comment]
@asv No problem at all. Thanks meeting the contribution guidelines! I know they can be painful but we appreciate it!

**Pull request merged**
