### PR TITLE
LICENSE: fill in copyright holder

### LINKED ISSUE #18: Copyright is missing
Dear containerd authors,

I would like to package this library for Debian, however I couldn't find a copyright anywhere. This should be mentioned in the `LICENSE` file as well, right now the copyright line there is just a template.

https://github.com/containerd/btrfs/blob/9874fdfff052afdf879a315799ab38609d85753f/LICENSE#L189

Thanks

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

Closes #18

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @caniszczyk @containerd/containerd-reviewers @containerd/containerd-maintainers

**Comment by caniszczyk** [comment]
I'd leave the year in, but LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Comment by stevvooe** [comment]
> I'd leave the year in

Didn't we make a different recommendation in the containerd project?

**Comment by stevvooe** [comment]
Actually, it has come to my attention that we need to leave the template in place and apply this to the files with `The containerd Authors` filled in.

cc @kunalkushwaha

**Comment by stevvooe** [comment]
I've updated this appropriately.

**Comment by crosbymichael** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
