### PR TITLE
Remove travis, vendor, update to go 1.16.x and actions/setup-go@v2

### PR DESCRIPTION
**Pull request by thaJeztah**
obsoletes https://github.com/containerd/btrfs/pull/26

Also removes a duplicate copyright header in cmd/btrfs-test

### CODE REVIEW

**Comment by thaJeztah** [comment]
After this is merged, I'll rebase https://github.com/containerd/btrfs/pull/30

**Review by fuweid — APPROVED** [review]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
