### PR TITLE
Move repo to go modules

### PR DESCRIPTION
**Pull request by chenrui333**
Issue tracker, https://github.com/containerd/containerd/issues/3031

### CODE REVIEW

**Comment by chenrui333** [comment]
Finally, it is passed :)

**Comment by estesp** [comment]
It seems like if we really want to move we should be changing `go get` to `go mod vendor` (in the `.travis.yml` script) so it actually uses the new `go.mod`?

**Comment by crosbymichael** [comment]
LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
